---
kind: pipeline
type: docker
name: linux-build

steps:
- name: linux-build
  image: wow-dependencies:v1.0
  commands:
  - make -j2 release-static-linux-x86_64

- name: discord linux notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: Linux build {{build.number}} complete. {{build.link}} 
  depends_on:
    - linux-build

- name: matrix linux notification
  image: plugins/matrix
  settings:
    homeserver: https://matrix.org
    roomid: tfuEmpojJyhMTMjNeN:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: Linux build {{build.number}} complete. {{build.link}}
  depends_on:
    - linux-build

---
kind: pipeline
type: ssh
name: mac-build

server:
  host:
    from_secret: mac-server
  user:
    from_secret: mac-user
  password:
    from_secret: mac-password

steps:
- name: mac-build
  commands:
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - export PATH=/usr/local/bin:$PATH
  - brew update
  - brew bundle --file=contrib/brew/Brewfile
  - make -j3 release-static