---
kind: pipeline
type: docker
name: linux-build

steps:
- name: linux-build
  image: wow-dependencies:v1.0
  commands:
  - make -j2 release-static-linux-x86_64

- name: discord linux notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: Linux build {{build.number}} complete. {{build.link}} 
  depends_on:
    - linux-build

- name: matrix linux notification
  image: plugins/matrix
  settings:
    homeserver: https://matrix.org
    roomid: tfuEmpojJyhMTMjNeN:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: Linux build {{build.number}} complete. {{build.link}}
  depends_on:
    - linux-build