---
kind: pipeline
type: docker
name: linux-build

steps:
- name: linux-build
  image: wow-dependencies:v1.0
  commands:
  - make -j2 release-static-linux-x86_64

---
kind: pipeline
type: ssh
name: mac-build

server:
  host:
    from_secret: mac-server
  user:
    from_secret: mac-user
  ssh_key:
    from_secret: ssh-key

steps:
- name: mac-build
  commands:
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - export PATH=/usr/local/bin:$PATH
  - brew update
  - brew bundle --file=contrib/brew/Brewfile
  - make -j3 release-static